services:
  postgres:
    image: postgres:15
    container_name: poliuni-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

volumes:
  poliuni-volume:
